In [226]:
import numpy as np
import random 

class KMeans:
    def __init__(self, k):
        self.k = k

    def fit(self, data):
        """
        :param data: numpy array of shape (k, ..., dims)
        """
        data = np.array(data,dtype=float)
        print(data.shape)
        self.dim = data.shape[-1]
        means = self._initialize_means(data)
        
        
        # TODO: Initialize Mixtures, then run EM algorithm until it converges.



    def _initialize_means(self, data):
        # TODO: Initialize cluster centers
        return np.reshape(np.random.sample(size = self.dim*self.k)*
                          (np.max(data)-np.min(data)) + 
                          np.min(data),
                          (self.k,self.dim))
        

    def predict(self, data):
        """
        :param data: numpy array of shape (k, ..., dims)
        :return: labels of each datapoint and it's mean
                 0 <= labels[i] <= k - 1
        """
        pass


def KMeansPlusPlus(KMeans):
    def _initialize_means(self, data):
        # TODO: Initialize cluster centers using K Means++ algorithm
        pass


In [227]:
a = np.array([[1,2],[3,4],[5,7],[1,2],[3,4],[5,7]])

In [228]:
a.shape[-1]

2

In [229]:
b = KMeans(10)

In [230]:
b.fit(data)

(500, 2)
[[-9.24142121 -6.61667929]
 [ 2.10624317 -2.70175927]
 [-9.18330089 -3.63918095]
 [-8.43510207  6.45351725]
 [ 0.6536921  -9.43676297]
 [ 1.5362184  -8.97245804]
 [-4.56947497  0.22590262]
 [-3.78810008 -5.87585452]
 [-7.43837979 -1.32661646]
 [ 0.15446025  5.5118632 ]]


In [217]:
data= np.load("data.npy")

In [79]:
data

array([[ 5.15474795e+00, -1.71789862e+00],
       [-6.63287109e+00,  2.67548044e-01],
       [-3.61724003e+00,  1.65131897e+00],
       [-3.81332705e+00,  1.22206739e+00],
       [ 7.59063842e-01,  6.57706386e+00],
       [-7.02986231e+00,  3.40395993e+00],
       [-8.41848416e+00,  1.40856083e+00],
       [ 5.87028522e+00, -4.64991652e-01],
       [-6.60190350e+00,  3.99074249e+00],
       [ 4.31228200e+00, -1.97547893e+00],
       [-8.14671265e+00,  1.70115695e+00],
       [-3.31372028e+00,  3.14888102e+00],
       [ 6.12846297e+00, -6.58080476e-01],
       [-6.53377691e+00,  4.83224717e+00],
       [-8.50179515e+00,  3.26858078e+00],
       [ 7.01536774e+00, -1.20209702e+00],
       [-7.42879558e+00,  1.36322417e+00],
       [-4.02974036e-01,  5.61364630e+00],
       [-1.75071894e+00, -1.20469746e+00],
       [-2.25982477e-01,  4.05852413e+00],
       [-6.10687357e+00,  6.67086093e+00],
       [-9.18820721e+00,  5.34648015e+00],
       [-7.79275441e+00,  1.65935674e+00],
       [-7.

In [165]:
a = np.array(np.random.normal(loc=9,size=(15,6)),dtype=int)
a[a>=10] = 10
a

array([[10, 10,  5,  8,  9, 10],
       [10,  8,  8,  8, 10,  7],
       [ 9,  9, 10,  9,  8,  9],
       [ 8,  8,  7,  8,  8,  8],
       [ 9, 10,  9,  7,  9,  9],
       [ 8,  9, 10, 10,  8,  7],
       [ 8, 10,  9,  8,  9,  7],
       [ 8,  8,  8,  8,  9, 10],
       [ 7,  8,  9,  8,  9,  8],
       [ 8,  7,  8,  9,  7,  8],
       [ 9,  9,  9,  9,  7,  8],
       [ 7, 10,  9,  7,  9,  9],
       [ 9,  9,  8,  9, 10,  8],
       [ 8,  8,  8,  7,  9,  9],
       [ 8,  8,  8, 10,  8, 10]])